# Something-something V1 Dataset
# https://20bn.com/datasets/something-something/v1


__sample_num_per_class__ = {
    "Holding something"                                                                                     :   986,                                            
    "Turning something upside down"                                                                         :   979 ,
    "Turning the camera left while filming something"                                                       :   924 ,                                                
    "Stacking number of something"                                                                          :   914 ,                            
    "Turning the camera right while filming something"                                                      :   914 ,                                        
    "Opening something"                                                                                     :   888 ,      
    "Approaching something with your camera"                                                                :   885 , 
    "Picking something up"                                                                                  :   877 ,        
    "Pushing something so that it almost falls off but doesn't"                                             :   873 ,        
    "Folding something"                                                                                     :   864 ,      
    "Moving something away from the camera"                                                                 :   863 ,          
    "Closing something"                                                                                     :   858 ,      
    "Moving away from something with your camera"                                                           :   850 ,      
    "Turning the camera downwards while filming something"                                                  :   845 ,      
    "Pushing something so that it slightly moves"                                                           :   841 ,      
    "Turning the camera upwards while filming something"                                                    :   839 ,          
    "Pretending to pick something up"                                                                       :   838 ,                  
    "Showing something to the camera"                                                                       :   838 ,                           
    "Moving something up"                                                                                   :   833 ,                  
    "Plugging something into something"                                                                     :   830 ,                  
    "Unfolding something"                                                                                   :   830 ,          
    "Putting something onto something"                                                                      :   828 ,              
    "Showing that something is empty"                                                                       :   827 ,        
    "Pretending to put something on a surface"                                                              :   825 ,       
    "Taking something from somewhere"                                                                       :   825 ,    
    "Putting something next to something"                                                                   :   824 ,
    "Moving something towards the camera"                                                                   :   821 ,
    "Showing a photo of something to the camera"                                                            :   820 ,                                                 
    "Pushing something with something"                                                                      :   815 ,                                
    "Throwing something"                                                                                    :   808 ,                                    
    "Pushing something from left to right"                                                                  :   802 ,                                        
    "Something falling like a feather or paper"                                                             :   801 ,                                
    "Throwing something in the air and letting it fall"                                                     :   801 ,                                                
    "Throwing something against something"                                                                  :   796 ,                                            
    "Lifting something with something on it"                                                                :   793 ,                            
    "Taking one of many similar things on the table"                                                        :   788 ,                                                
    "Showing something behind something"                                                                    :   785 ,                                
    "Putting something into something"                                                                      :   781 ,                                        
    "Tearing something just a little bit"                                                                   :   780 ,                                    
    "Moving something away from something"                                                                  :   779 ,                        
    "Tearing something into two pieces"                                                                     :   778 ,                                                    
    "Holding something next to something"                                                                   :   777 ,                                                
    "Pushing something from right to left"                                                                  :   777 ,                                                            
    "Putting something, something and something on the table"                                               :   776 ,                                    
    "Moving something closer to something"                                                                  :   775 ,                                        
    "Pretending to take something from somewhere"                                                           :   775 ,                                            
    "Pretending to put something next to something"                                                         :   774 ,                                                    
    "Uncovering something"                                                                                  :   773 ,                                        
    "Pouring something into something"                                                                      :   772 ,                                            
    "Putting something and something on the table"                                                          :   772 ,                                        
    "Something falling like a rock"                                                                         :   772 ,                                    
    "Moving something down"                                                                                 :   769 ,                            
    "Pulling something from right to left"                                                                  :   769 ,                                        
    "Throwing something in the air and catching it"                                                         :   767 ,                            
    "Tilting something with something on it until it falls off"                                             :   763 ,                                
    "Putting something in front of something"                                                               :   762 ,                                    
    "Pretending to turn something upside down"                                                              :   760 ,                                            
    "Putting something on a surface"                                                                        :   759 ,                                        
    "Pretending to throw something"                                                                         :   757 ,                                        
    "Covering something with something"                                                                     :   756 ,                                        
    "Showing something on top of something"                                                                 :   756 ,                                            
    "Squeezing something"                                                                                   :   753 ,                                    
    "Putting something similar to other things that are already on the table"                               :   752 ,          
    "Lifting up one end of something, then letting it drop down"                                            :   751 ,                  
    "Taking something out of something"                                                                     :   749 ,  
    "Moving part of something"                                                                              :   747 ,                          
    "Pulling something from left to right"                                                                  :   745 ,                          
    "Lifting something up completely without letting it drop down"                                          :   744 ,                          
    "Attaching something to something"                                                                      :   743 ,                  
    "Holding something in front of something"                                                               :   743 ,          
    "Moving something and something closer to each other"                                                   :   743 ,                      
    "Putting something behind something"                                                                    :   743 ,              
    "Pushing something so that it falls off the table"                                                      :   742 ,                              
    "Holding something over something"                                                                      :   735 ,          
    "Pretending to open something without actually opening it"                                              :   734 ,                      
    "Removing something, revealing something behind"                                                        :   732 ,                          
    "Hitting something with something"                                                                      :   729 ,                  
    "Moving something and something away from each other"                                                   :   727 ,                  
    "Touching (without moving) part of something"                                                           :   727 ,          
    "Pretending to put something into something"                                                            :   724 ,                              
    "Showing that something is inside something"                                                            :   724 ,                                          
    "Lifting something up completely, then letting it drop down"                                            :   721 ,                          
    "Pretending to take something out of something"                                                         :   720 ,                                              
    "Holding something behind something"                                                                    :   709 ,                                              
    "Laying something on the table on its side, not upright"                                                :   707 ,                                  
    "Poking something so it slightly moves"                                                                 :   700 ,                                          
    "Pretending to close something without actually closing it"                                             :   699 ,                                  
    "Putting something upright on the table"                                                                :   698 ,                                              
    "Dropping something in front of something"                                                              :   690 ,                                  
    "Dropping something behind something"                                                                   :   687 ,                                                                          
    "Lifting up one end of something without letting it drop down"                                          :   685 ,                                          
    "Rolling something on a flat surface"                                                                   :   682 ,                                      
    "Throwing something onto a surface"                                                                     :   677 ,                                                  
    "Showing something next to something"                                                                   :   671 ,                                                      
    "Dropping something onto something"                                                                     :   668 ,                                  
    "Stuffing something into something"                                                                     :   668 ,                                      
    "Dropping something into something"                                                                     :   662 ,                                  
    "Piling something up"                                                                                   :   662 ,                              
    "Letting something roll along a flat surface"                                                           :   660 ,                      
    "Twisting something"                                                                                    :   658 ,                                  
    "Spinning something that quickly stops spinning"                                                        :   643 ,                                  
    "Putting number of something onto something"                                                            :   636 ,                                      
    "Moving something across a surface without it falling down"                                             :   634 ,                                      
    "Putting something underneath something"                                                                :   634 ,                          
    "Plugging something into something but pulling it right out as you remove your hand"                    :   628 ,                                  
    "Dropping something next to something"                                                                  :   627 ,                              
    "Poking something so that it falls over"                                                                :   606 ,                                  
    "Spinning something so it continues spinning"                                                           :   593 ,                              
    "Poking something so lightly that it doesn't or almost doesn't move"                                    :   588 ,                                          
    "Wiping something off of something"                                                                     :   585 ,                                  
    "Moving something across a surface until it falls down"                                                 :   582 ,                                              
    "Pretending to poke something"                                                                          :   580 ,                                                          
    "Putting something that cannot actually stand upright upright on the table, so it falls on its side"    :   570 ,                                                            
    "Pulling something out of something"                                                                    :   566 ,                                
    "Scooping something up with something"                                                                  :   565 ,                    
    "Pretending to be tearing something that is not tearable"                                               :   562 ,                                                
    "Burying something in something"                                                                        :   543 ,                                        
    "Tipping something over"                                                                                :   542 ,                                            
    "Tilting something with something on it slightly so it doesn't fall down"                               :   533 ,                                            
    "Pretending to put something onto something"                                                            :   528 ,                                            
    "Bending something until it breaks"                                                                     :   522 ,                                                    
    "Letting something roll down a slanted surface"                                                         :   512 ,                                                    
    "Trying to bend something unbendable so nothing happens"                                                :   509 ,                                        
    "Bending something so that it deforms"                                                                  :   505 ,                                            
    "Digging something out of something"                                                                    :   503 ,                                        
    "Pretending to put something underneath something"                                                      :   502 ,                                
    "Putting something on a flat surface without letting it roll"                                           :   497 ,                                            
    "Putting something on the edge of something so it is not supported and falls down"                      :   479 ,                                
    "Pretending to put something behind something"                                                          :   471 ,                                        
    "Spreading something onto something"                                                                    :   471 ,                
    "Sprinkling something onto something"                                                                   :   466 ,                                            
    "Something colliding with something and both come to a halt"                                            :   463 ,                                    
    "Pushing something off of something"                                                                    :   462 ,                                        
    "Putting something that can't roll onto a slanted surface, so it stays where it is"                     :   453 ,                                                            
    "Lifting a surface with something on it until it starts sliding down"                                   :   451 ,                                        
    "Pretending or failing to wipe something off of something"                                              :   433 ,                                                                
    "Trying but failing to attach something to something because it doesn't stick"                          :   433 ,                                                
    "Pulling something from behind of something"                                                            :   427 ,                                    
    "Pushing something so it spins"                                                                         :   423 ,                                        
    "Pouring something onto something"                                                                      :   420 ,                                
    "Pulling two ends of something but nothing happens"                                                     :   416 ,                            
    "Moving something and something so they pass each other"                                                :   413 ,                                                
    "Pretending to sprinkle air onto something"                                                             :   413 ,                                            
    "Putting something that can't roll onto a slanted surface, so it slides down"                           :   405 ,                                                                
    "Something colliding with something and both are being deflected"                                       :   395 ,                            
    "Pretending to squeeze something"                                                                       :   386 ,
    "Pulling something onto something"                                                                      :   367 ,                                    
    "Putting something onto something else that cannot support it so it falls down"                         :   362 ,                                                        
    "Lifting a surface with something on it but not enough for it to slide down"                            :   358 ,                                        
    "Pouring something out of something"                                                                    :   358 ,                                        
    "Moving something and something so they collide with each other"                                        :   346 ,                                        
    "Tipping something with something in it over, so something in it falls out"                             :   341 ,                                                
    "Letting something roll up a slanted surface, so it rolls back down"                                    :   339 ,                                        
    "Pretending to scoop something up with something"                                                       :   318 ,                                            
    "Pretending to pour something out of something, but something is empty"                                 :   311 ,                                                    
    "Pulling two ends of something so that it gets stretched"                                               :   294 ,                            
    "Failing to put something into something because something does not fit"                                :   290 ,                            
    "Pretending or trying and failing to twist something"                                                   :   288 ,                    
    "Trying to pour something into something, but missing so it spills next to it"                          :   282 ,                    
    "Something being deflected from something"                                                              :   277 ,                
    "Poking a stack of something so the stack collapses"                                                    :   273 ,                                                
    "Spilling something onto something"                                                                     :   267 ,                            
    "Pulling two ends of something so that it separates into two pieces"                                    :   245 ,                            
    "Pouring something into something until it overflows"                                                   :   229 ,                    
    "Pretending to spread air onto something"                                                               :   220 ,                                    
    "Twisting (wringing) something wet until water comes out"                                               :   219 ,                                    
    "Poking a hole into something soft"                                                                     :   217 ,            
    "Spilling something next to something"                                                                  :   207 ,                                        
    "Poking a stack of something without the stack collapsing"                                              :   206 ,                                            
    "Putting something onto a slanted surface but it doesn't glide down"                                    :   183 ,                                                                
    "Pushing something onto something"                                                                      :   170 ,                                                    
    "Poking something so that it spins around"                                                              :   141 ,                                                
    "Spilling something behind something"                                                                   :   121 ,                                            
    "Poking a hole into some substance"                                                                     :   77  ,                                                            
}

__classes__ = __sample_num_per_class__.keys()

# generating label mapping
# map "Doing other things" cid 0
cids = list(range(len(__classes__)))
label_map = dict(zip(__classes__, cids))


if __name__ == "__main__":
    print(cids)